In [27]:
import numpy as np

a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


## Vectorization vs Non Vectorization

In [26]:
import time 

a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic = time.time()
c = np.dot(a,b)
toc = time.time()

print(c)
print("Vectorized verison: " + str(1000*(toc-tic)) + "ms")

# NON Vectorized version

c = 0
tic = time.time()
for i in range(1000000):
    c += a[i] * b[i]

toc = time.time()
print(c)
print("Non-Vectorized version: " + str(1000 *(toc-tic)) + "ms")

250142.97835865628
Vectorized verison: 11.959075927734375ms
250142.97835865733
Non-Vectorized version: 512.4008655548096ms


## Broadcasting

In [28]:
A = np.array([
    [56.0, 0.0, 4.4, 68.0],
    [1.2, 104.0, 52.0, 8.0],
    [1.8, 135.0, 99.0, 0.9]
])

print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [37]:
cal = A.sum(axis=0) # axis = 0 for vertical sum / column wise  OR 1 for row wise
print(cal)

[ 59.  239.  155.4  76.9]


In [38]:
percentage = 100*A/cal.reshape(1,4) # whats the need for .reshape(1,4) ? redundant - but it is broadcasting cal to A
# how (3,4) be divided by (1,4) ? 
print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


---------------